name: Markdown and other text documentation linting
run-name: Markdown linting
on: [push, pull_request]

jobs:
  markdown-lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: './**/*.md'
          ignore: '.github/**'
          config: '.markdownlint.json'
